# Generated by Django 5.2.14 on 2026-06-16 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokupatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_buyed', models.BooleanField(default=False)),
                ('pokupatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3django.pokupatel')),
            ],
        ),
        migrations.CreateModel(
            name='TovarMnM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('korzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3django.korzina')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3django.tovar')),
            ],
        ),
        migrations.AddField(
            model_name='korzina',
            name='tovar',
            field=models.ManyToManyField(through='lab3django.TovarMnM', to='lab3django.tovar'),
        ),
    ]
