# Generated by Django 5.2.14 on 2026-06-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TovarMnM',
            new_name='Tovar_M',
        ),
    ]
