# Generated by Django 5.2.14 on 2026-06-15 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzina',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pokupatel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tovar',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
