# Generated by Django 5.2.14 on 2026-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2django', '0002_korzina_created_at_pokupatel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzina',
            name='is_buyed',
            field=models.BooleanField(default=False),
        ),
    ]
