# Generated by Django 5.2.14 on 2026-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField()),
                ('rating', models.IntegerField()),
                ('title', models.CharField()),
                ('genre', models.CharField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
